Feature/50 topics request
SENG499-Company-4/Frontend pull request #57
Opened 2022-06-20 20:29 UTC by Ahnaf-Ahmed

Changes
---
Added Rich's requested topic course request section. This is done by removing the associated department topics course from the general list and then adding it back when the form is submitted. There is a section below the general course slection to request a topics course where a professor can check a box and input the name of a topics course. On submission topics course will either have  "can teach" and "very willing" if selected or "can't teach" and "not willing" if not selected.

Testing
---
Manual testing by verifying that topics course does not appear in general list and does appear on submission in output.

Seng 480 does not appear in list
![image](https://user-images.githubusercontent.com/28603391/174673591-3ac8848b-ce41-4c12-8c81-4f5f889576cc.png)

Seng 480 appears in console output as well as topics title
![image](https://user-images.githubusercontent.com/28603391/174673796-ab01f368-7172-4722-bdad-17fee3bc075e.png)

Linked Issue
---
https://github.com/SENG499-Company-4/Frontend/issues/50

Additional Info
---
Only removes and then adds departmental topics courses (ex if a prof is associated with ECE then SENG 480 will not be removed or added back). This is due to the understanding that the list will only be classes for the prof's department (SENG courses and SENG 480 won't be in an ECE prof's list).

2022-06-20 21:33 UTC, sam-warren approved these changes
Great work!

2022-06-21 19:58 UTC, bmazerolle requested changes
This looks like a really good start, other than my comments I have one suggestion:

Talked to the Alg 1 team yesterday, and for MVP we do not plan on supporting ECE and SENG schedules as distinct entities so we should first implement everything together. Because of this, I think we should change our approach to deciding which course number applies to the topics course selector. I would make two changes
* Remove all topics courses from the course list above (I still see A/B/C etc. courses in it)
* Add a dropdown selector to the left of "Topics Course Title" input that allows the user to select one of "ECE 496", "CSC 482" or "SENG 480". That way the prof can just self declare which one they think it applies to

2022-06-21 19:58 UTC, bmazerolle commented on app/src/components/organisms/SurveyForm.tsx
> +    console.log('topic is now: ', topic);
Remove

2022-06-21 19:58 UTC, bmazerolle commented on app/src/components/organisms/SurveyForm.tsx
> +          <Stack direction="row" spacing={2}>
Move this to just below the course list (top of the section), since it has more to do with course selection than anything else

2022-06-23 06:12 UTC, Ahnaf-Ahmed commented
Some courses will still have letters in them but they aren't topics courses but rather just have letters (like 349a for numerical analysis or part 1 and 2 courses)

2022-06-24 06:18 UTC, bmazerolle approved these changes
Really nice. Admittedly we may end up removing that departmental fanciness you added that restricts the topics course # but for now this looks great for demo.

2022-06-24 16:54 UTC, merged