Added section select to schedule generate page
SENG499-Company-4/Frontend pull request #81
Opened 2022-07-05 21:16 UTC by Ahnaf-Ahmed

Changes
---
Added a selection for number of sections to be offered. Defaults to 1 with a max of 6

Testing
---
Manual testing by outputting to console log

Linked Issue
---
https://github.com/SENG499-Company-4/Frontend/issues/80

Additional Info
---
![image](https://user-images.githubusercontent.com/28603391/177417949-213dab93-e7d8-4a87-a0fc-8176b6f61245.png)

2022-07-06 02:08 UTC, bmazerolle requested changes
The code itself looks good but I think we should work on the UI a bit - it'll get very big and ugly quickly if Rich adds a lot of courses. Try to add the "sections" dropdown selector inline with the the classes that are selected, in the search bar.

Basically I would get rid of the grid you added, and just make each selected course in search bar larger, and containing the section count selector inline in that course object.

2022-07-06 02:08 UTC, bmazerolle commented on app/src/components/pages/ScheduleGenerate.tsx
> +                            {[1, 2, 3, 4, 5, 6].map((amount) => (
why 6?

2022-07-06 21:19 UTC, Ahnaf-Ahmed commented
> The code itself looks good but I think we should work on the UI a bit - it'll get very big and ugly quickly if Rich adds a lot of courses. Try to add the "sections" dropdown selector inline with the the classes that are selected, in the search bar.
> 
> Basically I would get rid of the grid you added, and just make each selected course in search bar larger, and containing the section count selector inline in that course object.

Just to be clear, in the chips in the search bar? 
![image](https://user-images.githubusercontent.com/28603391/177634162-fb284c57-c025-4653-80de-447f68fd26ff.png)

If that's the case I feel like those are really small and the selection should at least be below the search bar. Even if said chips are made larger, I think we'll have a similar problem of it getting big and ugly with a lot of courses added in but now with a very large search bar instead of separate part of the page.

2022-07-07 06:57 UTC, bmazerolle requested changes
Nice job. I have two requested changes:
- Can you reset the course list after submission? Ideally the whole page. Could either clear the list or reload the page.
- Increase the max to 10, I think that will be big but safer than 66 since classes keep getting bigger

2022-07-07 06:57 UTC, bmazerolle commented on app/src/components/pages/ScheduleGenerate.tsx
> +                            {[1, 2, 3, 4, 5, 6].map((amount) => (
Ok I would change to 10 just to be safe, no harm in a bigger number

2022-07-07 22:20 UTC, Ahnaf-Ahmed commented
> Nice job. I have two requested changes:
> 
> * Can you reset the course list after submission? Ideally the whole page. Could either clear the list or reload the page.
> * Increase the max to 10, I think that will be big but safer than 66 since classes keep getting bigger

Page now refreshes upon clicking OKin the dialog box 
![image](https://user-images.githubusercontent.com/28603391/177881077-0e550ffd-1142-45a7-9e2f-176be9ea6a3f.png)
 and section max is now 10

2022-07-07 22:56 UTC, bmazerolle commented on app/src/components/pages/ScheduleGenerate.tsx
> +                                {amount != 0 ? amount : 'Algorithm Determined'}
Just to have an option for not setting the count

2022-07-07 22:57 UTC, bmazerolle approved these changes

2022-07-08 00:46 UTC, merged