Feature/74 update registration page
SENG499-Company-4/Frontend pull request #82
Opened 2022-07-06 00:47 UTC by Hexuan-Z

Changes
---
On registration page:
- Remove "UVIC ID" / V number field
- Add drop down menu to choose between three faculties: CSC, SENG and ECE

Testing
---
Manual testing

Linked Issue
---
https://github.com/SENG499-Company-4/Frontend/issues/74

Additional Info
---
![12](https://user-images.githubusercontent.com/83629521/177439424-88b3a7cc-349d-4557-8c4e-e329b3b7c8d2.PNG)

2022-07-06 00:58 UTC, sam-warren requested changes
Looks good - just a few programmatic changes

2022-07-06 00:58 UTC, sam-warren commented on app/src/components/pages/Register.tsx
>    }, [formData.password, formData.confirmPassword, formData.vnum.length]);
Need to update this dependency array to remove vnum and add faculty.

2022-07-06 00:58 UTC, sam-warren commented on app/src/components/pages/Register.tsx
>  interface IRegisterForm {
Update registration form interface, replace vnum with faculty, same goes for the formData object on line 21 - we need to remove vnum from the component and replace it with the faculty dropdown value.

2022-07-08 04:36 UTC, Ahnaf-Ahmed requested changes
Some small changes along with Sam's and I think you're good to go,

2022-07-08 20:35 UTC, sam-warren approved these changes

2022-07-08 20:40 UTC, Ahnaf-Ahmed approved these changes
Looks great now!

2022-07-08 20:42 UTC, merged